export interface CountryPhoneCode {
    countryFullName: string,
    countryShortName: string,
    code: string
}

export const countryPhoneCodes: Array<CountryPhoneCode> =
[
    {countryFullName: 'Albania', countryShortName: 'AL', code: '+355'},
    {countryFullName: 'Andorra', countryShortName: 'AD', code: '+376'},
    {countryFullName: 'Austria', countryShortName: 'AT', code: '+43'},
    {countryFullName: 'Belarus', countryShortName: 'BY', code: '+375'},
    {countryFullName: 'Belgium', countryShortName: 'BE', code: '+32'},
    {countryFullName: 'Bosnia and Herzegovina', countryShortName: 'BA', code: '+387'},
    {countryFullName: 'Bulgaria', countryShortName: 'BG', code: '+359'},
    {countryFullName: 'Croatia', countryShortName: 'HR', code: '+385'},
    {countryFullName: 'Cyprus', countryShortName: 'CY', code: '+357'},
    {countryFullName: 'Czech Republic', countryShortName: 'CZ', code: '+420'},
    {countryFullName: 'Denmark', countryShortName: 'DK', code: '+45'},
    {countryFullName: 'Estonia', countryShortName: 'EE', code: '+372'},
    {countryFullName: 'Finland', countryShortName: 'FI', code: '+358'},
    {countryFullName: 'France', countryShortName: 'FR', code: '+33'},
    {countryFullName: 'Germany', countryShortName: 'DE', code: '+49'},
    {countryFullName: 'Greece', countryShortName: 'GR', code: '+30'},
    {countryFullName: 'Hungary', countryShortName: 'HU', code: '+36'},
    {countryFullName: 'Iceland', countryShortName: 'IS', code: '+354'},
    {countryFullName: 'Ireland', countryShortName: 'IE', code: '+353'},
    {countryFullName: 'Italy', countryShortName: 'IT', code: '+39'},
    {countryFullName: 'Kosovo', countryShortName: 'XK', code: '+383'},
    {countryFullName: 'Latvia', countryShortName: 'LV', code: '+371'},
    {countryFullName: 'Liechtenstein', countryShortName: 'LI', code: '+423'},
    {countryFullName: 'Lithuania', countryShortName: 'LT', code: '+370'},
    {countryFullName: 'Luxembourg', countryShortName: 'LU', code: '+352'},
    {countryFullName: 'Malta', countryShortName: 'MT', code: '+356'},
    {countryFullName: 'Moldova', countryShortName: 'MD', code: '+373'},
    {countryFullName: 'Monaco', countryShortName: 'MC', code: '+377'},
    {countryFullName: 'Montenegro', countryShortName: 'ME', code: '+382'},
    {countryFullName: 'Netherlands', countryShortName: 'NL', code: '+31'},
    {countryFullName: 'North Macedonia', countryShortName: 'MK', code: '+389'},
    {countryFullName: 'Norway', countryShortName: 'NO', code: '+47'},
    {countryFullName: 'Poland', countryShortName: 'PL', code: '+48'},
    {countryFullName: 'Portugal', countryShortName: 'PT', code: '+351'},
    {countryFullName: 'Romania', countryShortName: 'RO', code: '+40'},
    {countryFullName: 'Russia', countryShortName: 'RU', code: '+7'},
    {countryFullName: 'San Marino', countryShortName: 'SM', code: '+378'},
    {countryFullName: 'Serbia', countryShortName: 'RS', code: '+381'},
    {countryFullName: 'Slovakia', countryShortName: 'SK', code: '+421'},
    {countryFullName: 'Slovenia', countryShortName: 'SI', code: '+386'},
    {countryFullName: 'Spain', countryShortName: 'ES', code: '+34'},
    {countryFullName: 'Sweden', countryShortName: 'SE', code: '+46'},
    {countryFullName: 'Switzerland', countryShortName: 'CH', code: '+41'},
    {countryFullName: 'Turkey', countryShortName: 'TR', code: '+90'},
    {countryFullName: 'Ukraine', countryShortName: 'UA', code: '+380'},
    {countryFullName: 'United Kingdom', countryShortName: 'GB', code: '+44'},
    {countryFullName: 'Vatican City', countryShortName: 'VA', code: '+379'},
]


